import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // TechHub SF products (sellerId: 1)
        {
            sellerId: 1,
            title: 'iPhone 15 Pro',
            description: 'The most advanced iPhone ever with titanium design, A17 Pro chip, and pro camera system',
            priceCents: 99999,
            currency: 'USD',
            stock: 25,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1696446701796-da61225697cc?q=80&w=1000']),
            tags: JSON.stringify(['smartphone', 'apple', 'premium']),
            latitude: 37.7749,
            longitude: -122.4194,
            city: 'San Francisco',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            sellerId: 1,
            title: 'MacBook Air M3',
            description: 'Supercharged by the M3 chip, the new MacBook Air is strikingly thin and fast',
            priceCents: 129999,
            currency: 'USD',
            stock: 15,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000']),
            tags: JSON.stringify(['laptop', 'apple', 'business']),
            latitude: 37.7749,
            longitude: -122.4194,
            city: 'San Francisco',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            sellerId: 1,
            title: 'AirPods Pro 2',
            description: 'Next-level Active Noise Cancellation and Adaptive Transparency reduce more external noise',
            priceCents: 24999,
            currency: 'USD',
            stock: 50,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=1000']),
            tags: JSON.stringify(['headphones', 'wireless', 'apple']),
            latitude: 37.7749,
            longitude: -122.4194,
            city: 'San Francisco',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            sellerId: 1,
            title: 'Samsung Galaxy S24',
            description: 'Capture stunning night shots with Nightography and enjoy longer battery life',
            priceCents: 79999,
            currency: 'USD',
            stock: 30,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?q=80&w=1000']),
            tags: JSON.stringify(['smartphone', 'samsung', 'android']),
            latitude: 37.7749,
            longitude: -122.4194,
            city: 'San Francisco',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            sellerId: 1,
            title: 'Dell XPS 13',
            description: 'The smallest 13-inch laptop with stunning 4-sided InfinityEdge display',
            priceCents: 109999,
            currency: 'USD',
            stock: 20,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000']),
            tags: JSON.stringify(['laptop', 'dell', 'ultrabook']),
            latitude: 37.7749,
            longitude: -122.4194,
            city: 'San Francisco',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-19').toISOString(),
        },
        // StyleWorks LA products (sellerId: 2)
        {
            sellerId: 2,
            title: 'Designer Handbag',
            description: 'Luxury leather handbag with premium finish and spacious interior',
            priceCents: 29999,
            currency: 'USD',
            stock: 12,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000']),
            tags: JSON.stringify(['fashion', 'luxury', 'handbag']),
            latitude: 34.0522,
            longitude: -118.2437,
            city: 'Los Angeles',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            sellerId: 2,
            title: 'Casual Sneakers',
            description: 'Comfortable everyday sneakers made from breathable materials',
            priceCents: 12999,
            currency: 'USD',
            stock: 40,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000']),
            tags: JSON.stringify(['shoes', 'casual', 'comfortable']),
            latitude: 34.0522,
            longitude: -118.2437,
            city: 'Los Angeles',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-21').toISOString(),
        },
        {
            sellerId: 2,
            title: 'Leather Jacket',
            description: 'Genuine leather jacket with modern fit and classic styling',
            priceCents: 24999,
            currency: 'USD',
            stock: 8,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=1000']),
            tags: JSON.stringify(['clothing', 'leather', 'jacket']),
            latitude: 34.0522,
            longitude: -118.2437,
            city: 'Los Angeles',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            sellerId: 2,
            title: 'Sunglasses Set',
            description: 'UV protection sunglasses with polarized lenses and stylish frame',
            priceCents: 8999,
            currency: 'USD',
            stock: 60,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000']),
            tags: JSON.stringify(['accessories', 'sunglasses', 'uv-protection']),
            latitude: 34.0522,
            longitude: -118.2437,
            city: 'Los Angeles',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-23').toISOString(),
        },
        // ElectroMart Chicago products (sellerId: 3)
        {
            sellerId: 3,
            title: 'Wireless Mouse',
            description: 'Ergonomic wireless mouse with precision tracking and long battery life',
            priceCents: 2999,
            currency: 'USD',
            stock: 100,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1000']),
            tags: JSON.stringify(['computer', 'mouse', 'wireless']),
            latitude: 41.8781,
            longitude: -87.6298,
            city: 'Chicago',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-24').toISOString(),
        },
        {
            sellerId: 3,
            title: 'Gaming Keyboard',
            description: 'RGB mechanical gaming keyboard with customizable backlighting',
            priceCents: 7999,
            currency: 'USD',
            stock: 45,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1595044426077-d36d9239fb5b?q=80&w=1000']),
            tags: JSON.stringify(['gaming', 'keyboard', 'rgb']),
            latitude: 41.8781,
            longitude: -87.6298,
            city: 'Chicago',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            sellerId: 3,
            title: 'USB-C Hub',
            description: '7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader and PD charging',
            priceCents: 4999,
            currency: 'USD',
            stock: 75,
            photos: JSON.stringify(['https://images.unsplash.com/photo-1527814050087-3793815479db?q=80&w=1000']),
            tags: JSON.stringify(['accessories', 'usb', 'connectivity']),
            latitude: 41.8781,
            longitude: -87.6298,
            city: 'Chicago',
            country: 'United States',
            isActive: true,
            createdAt: new Date('2024-01-26').toISOString(),
        }
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});